name: CI

on:
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - master
      - development
      

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry build system 
        run: |
          pip install -U pip 
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          make test